### ISSUE TITLE
パッケージの衝突

### ISSUE THREAD

**Issue by ghost** [Hayao0819/wfa#1]
![スクリーンショット](https://imgur.com/YZLEjys.png)
このリポジトリをcloneしてpkgbuildのあるデイレクトリに移動してmakepkgを実行してインストールしました
エラーでインストールできませんでした

**Comment by Hayao0819** [comment]
`google-chrome`はサポートしています。`wfa-git`のようなmakepkgが`pkgver`を更新するようなパッケージはまだサポートされていません。

**Comment by ghost** [comment]
google-chromeはインストールできるということですか？

**Comment by Hayao0819** [comment]
先程のコミットで修正しました
現在こちらの開発環境では`google-chrome`と`wfa-git`ともにインストールできるはずです。

**Comment by ghost** [comment]
成功しました
ありがとうございました
